name: reviz_develop
description: Reviz - randevu & araç yönetimi
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

# Uygulama sürümü
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Medya / görsel
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3

  # Konum
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  permission_handler: ^11.3.1

  # Backend
  supabase_flutter: ^2.6.0
  flutter_dotenv: 5.1.0
  http: ^1.2.2

  # Durum / yardımcılar (gerekirse)
  collection: ^1.18.0
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Tüm görselleri yakalamak için kök assets klasörü
  assets:
    - assets/
    # Eğer alt klasörler kullanıyorsan (örn. assets/images/), yukarıdaki satır zaten kapsar.
    # İstersen ayrı ayrı da açabilirsin:
    # - assets/images/
    # - assets/icons/

  # Eğer Roboto / Roboto Flex / Poppins’i lokal kullanmak istersen,
  # fonts bölümünü aç ve dosyaları assets/fonts/ altına koy.
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: Roboto Flex
  #     fonts:
  #       - asset: assets/fonts/RobotoFlex-VariableFont.ttf
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
